apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-vgqmgryl
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-vgqmgryl:66f48ecd074b1aa7f29dc2262c296a475298c379@sha256:e5d4124a69bd282c5bc9ce28cb56521bd6b40947931b9393cbeb2c54f56ba421
          name: container-image
